#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure_ac
# autospec version: v13
# autospec commit: dc0ff31
#
Name     : subunit
Version  : 1.4.4
Release  : 87
URL      : https://github.com/testing-cabal/subunit/archive/1.4.4/subunit-1.4.4.tar.gz
Source0  : https://github.com/testing-cabal/subunit/archive/1.4.4/subunit-1.4.4.tar.gz
Summary  : Subunit output listener for the CPPUnit test library.
Group    : Development/Tools
License  : Apache-2.0
Requires: subunit-lib = %{version}-%{release}
Requires: subunit-license = %{version}-%{release}
BuildRequires : file
BuildRequires : pkgconfig(check)
BuildRequires : pkgconfig(cppunit)
BuildRequires : pypi(iso8601)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
#  subunit C++ bindings.
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

%package dev
Summary: dev components for the subunit package.
Group: Development
Requires: subunit-lib = %{version}-%{release}
Provides: subunit-devel = %{version}-%{release}
Requires: subunit = %{version}-%{release}

%description dev
dev components for the subunit package.


%package lib
Summary: lib components for the subunit package.
Group: Libraries
Requires: subunit-license = %{version}-%{release}

%description lib
lib components for the subunit package.


%package license
Summary: license components for the subunit package.
Group: Default

%description license
license components for the subunit package.


%prep
%setup -q -n subunit-1.4.4
cd %{_builddir}/subunit-1.4.4
pushd ..
cp -a subunit-1.4.4 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1720028382
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%reconfigure --disable-static
make  %{?_smp_mflags}
unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%reconfigure --disable-static
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1720028382
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/subunit
cp %{_builddir}/subunit-%{version}/Apache-2.0 %{buildroot}/usr/share/package-licenses/subunit/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3 PERL_INSTALLDIRS=vendor
popd
GOAMD64=v2
%make_install PERL_INSTALLDIRS=vendor
## Remove excluded files
rm -f %{buildroot}*/usr/lib/perl5/5.20.0/x86_64-linux/perllocal.pod
rm -f %{buildroot}*/usr/bin/subunit-1to2
rm -f %{buildroot}*/usr/bin/subunit2csv
rm -f %{buildroot}*/usr/bin/subunit2gtk
rm -f %{buildroot}*/usr/bin/subunit2junitxml
rm -f %{buildroot}*/usr/bin/subunit2pyunit
rm -f %{buildroot}*/usr/bin/subunit-2to1
rm -f %{buildroot}*/usr/bin/subunit-filter
rm -f %{buildroot}*/usr/bin/subunit-ls
rm -f %{buildroot}*/usr/bin/subunit-notify
rm -f %{buildroot}*/usr/bin/subunit-output
rm -f %{buildroot}*/usr/bin/subunit-stats
rm -f %{buildroot}*/usr/bin/subunit-tags
rm -f %{buildroot}*/usr/bin/tap2subunit
## install_append content
rm -rfv %{buildroot}/usr/lib/python3*/site-packages/subunit
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/subunit/SubunitTestProgressListener.h
/usr/include/subunit/child.h
/usr/lib64/libcppunit_subunit.so
/usr/lib64/libsubunit.so
/usr/lib64/pkgconfig/libcppunit_subunit.pc
/usr/lib64/pkgconfig/libsubunit.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libcppunit_subunit.so.0.0.0
/V3/usr/lib64/libsubunit.so.0.0.0
/usr/lib64/libcppunit_subunit.so.0
/usr/lib64/libcppunit_subunit.so.0.0.0
/usr/lib64/libsubunit.so.0
/usr/lib64/libsubunit.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/subunit/2b8b815229aa8a61e483fb4ba0588b8b6c491890
